cmake_minimum_required(VERSION 3.17)
project(SlidingWindow)

set(CMAKE_CXX_STANDARD 17)
include_directories(util)
add_executable(SlidingWindow main.cpp test_factory.h util/util.h L3_lengthOfLongestSubstring/L3_lengthOfLongestSubstring.cpp L3_lengthOfLongestSubstring/L3_lengthOfLongestSubstring.h L30_findSubstring/L30_findSubstring.cpp L30_findSubstring/L30_findSubstring.h L76_minWindow/L76_minWindow.cpp L76_minWindow/L76_minWindow.h L187_findRepeatedDnaSequences/L187_findRepeatedDnaSequences.cpp L187_findRepeatedDnaSequences/L187_findRepeatedDnaSequences.h L209_minSubArrayLen/L209_minSubArrayLen.cpp L209_minSubArrayLen/L209_minSubArrayLen.h L219_containsNearbyDuplicate/L219_containsNearbyDuplicate.cpp L219_containsNearbyDuplicate/L219_containsNearbyDuplicate.h)